version: "3.3"

volumes:
  kong_data: {}

services:
  kong:
    build:
      context: ./
    volumes:
      - ./kong-declarative-config.yml:/tmp/kong-declarative-config.yml
      - ./kong/plugins/myplugin:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-myplugin/1.0.0-1/lua/kong/plugins/kong-plugin-myplugin
      - ./kong/plugins/myplugin:/usr/local/share/lua/5.1/kong/plugins/kong-plugin-myplugin
      - ./kong/plugins/js-hello:/usr/local/kong/plugins/js-plugins
    environment:
      KONG_DATABASE: "off"
      KONG_PLUGINSERVER_NAMES: js
      KONG_PLUGINSERVER_JS_SOCKET: /usr/local/kong/js_pluginserver.sock
      KONG_PLUGINSERVER_JS_START_CMD: /usr/lib/node_modules/kong-pdk/bin/kong-js-pluginserver -d /usr/local/kong/plugins/js-plugins
      KONG_PLUGINSERVER_JS_QUERY_CMD: /usr/lib/node_modules/kong-pdk/bin/kong-js-pluginserver -d /usr/local/kong/plugins/js-plugins --dump-all-plugins
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,kong-plugin-myplugin,js-hello,js-body-validation
    ports:
      - 8000:8000
      - 8001:8001
      - 8444:8444
      - 8443:8443
