_format_version: "2.1"

services:
  - name: my-service
    url: http://mockbin.org/bin/eab73e0e-f603-41ab-b9a3-91cab0422917
    plugins:
      - name: kong-plugin-myplugin
      - name: js-hello
        config:
          message: Bovino is here!!!
    routes:
      - name: get-post-data
        methods: [GET, POST]
        paths: [/v1/my-plugin-data]
      - name: only-post-https-data
        methods: [POST]
        protocols: [https]
        paths: [/v2/my-plugin-data]
      - name: post-data-http
        methods: [POST]
        protocols: [http]
        paths: [/v3/my-plugin-data]
        plugins:
          - name: js-body-validation
